# Generated by Django 5.1.1 on 2024-10-08 03:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coordinates', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PreplotLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaded', models.BooleanField(default=False)),
                ('preplot', models.IntegerField()),
                ('shotpoint1', models.IntegerField(default=0)),
                ('eastings1', models.FloatField()),
                ('northings1', models.FloatField()),
                ('latitude1', models.FloatField()),
                ('longitude1', models.FloatField()),
                ('shotpoint2', models.IntegerField(default=0)),
                ('eastings2', models.FloatField()),
                ('northings2', models.FloatField()),
                ('latitude2', models.FloatField()),
                ('longitude2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PreplotShotPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shotpoint', models.IntegerField()),
                ('easting', models.FloatField()),
                ('northing', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('preplot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppsp', to='planner.preplotline')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('pass_number', models.IntegerField()),
                ('sequence_number', models.IntegerField()),
                ('linename', models.CharField(max_length=255, null=True)),
                ('preplot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='planner.preplotline')),
            ],
        ),
        migrations.CreateModel(
            name='AcquisitionShotPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp', models.IntegerField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('east', models.FloatField()),
                ('north', models.FloatField()),
                ('depth', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('zlat1', models.FloatField()),
                ('zlon1', models.FloatField()),
                ('zlat2', models.FloatField()),
                ('zlon2', models.FloatField()),
                ('zlat3', models.FloatField()),
                ('zlon3', models.FloatField()),
                ('mean_lat', models.FloatField()),
                ('mean_lon', models.FloatField()),
                ('sequence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='planner.sequence')),
            ],
        ),
    ]
